name: Deploy and Test Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: automation

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Debug secrets
      run: |
        echo "AWS_REGION is set: ${{ secrets.AWS_REGION != '' }}"
        echo "ECR Repository: ${{ secrets.AWS_ECR_REPOSITORY != '' }}"

    - name: Install dependencies
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build the project
      env:
        AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        AWS_ECR_REPOSITORY_URL: ${{ secrets.AWS_ECR_REPOSITORY_URL }}
        IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
        AWS_LAMBDA_FUNCTION_NAME: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
        AWS_SERVICE_NAME: ${{ secrets.AWS_SERVICE_NAME }}
      run: npm run build

    - name: Deploy to ECR
      run: npm run deploy:ecr

    - name: Deploy Lambda
      run: npm run deploy

    - name: Invoke Lambda function
      run: npm run invoke
